__author__ = 'scott'

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
global sum
sum = 0

def evenCheck(num):
    global sum
    if num % 2 == 0:
        sum = sum + num

def fibonacci(first, second):
    next = 0

    evenCheck(first)
    evenCheck(second)

    while next <= 4000000:
        next = first + second

        evenCheck(next)

        first = second
        second = next

    print sum

fibonacci(1,2)

#4613732